### ISSUE TITLE
Update angular dependencies to 2.1.0

### ISSUE THREAD

**Issue by mohammedzamakhan** [tahaipek/angular2-university-domains-list#1]

**Comment by tahaipek** [comment]
Updated 
- Angular Dependencies 2.0.1 to 2.1.0
- Angular CLI .beta15 to .beta17

@mohammedzamakhan 
#https://github.com/tahaipek/angular2-university-domains-list/commit/b7bc2c8d0bc12e4fe5b68b195480e7b2d2ce60ec
